src/apps/bshop/contrib/wishlists/urls.py
from django.conf.urls import patterns, url

from .import views


urlpatterns = patterns('',
    url(r'^$',
        views.UserWishlistsView.as_view(), name='wishlist'),
    url(r'^(?P<wid>\d+)/$',
        views.WishlistView.as_view(), name='wishlist_items'),
    url(r'^add/$',
        views.WishlistCreateView.as_view(), name='wishlist_add'),
    url(r'^delete/(?P<pk>\d+)/$',
        views.WishlistDeleteView.as_view(), name='wishlist_delete'),
    url(r'^edit/(?P<pk>\d+)/$',
        views.WishlistEditView.as_view(), name='wishlist_edit'),
    url(r'^add-item/(?P<ctype>\d+)/(?P<oid>\d+)/$',
        views.WishlistAddView.as_view(), name='wishlist_add_item'),
    url(r'^add-item/(?P<ctype>\d+)/(?P<oid>\d+)/(?P<wid>\d+)/$',
        views.WishlistAddView.as_view(), name='wishlist_add_item_concrete'),
    url(r'^clear/(?P<wid>\d+)/$',
        views.WishlistClearView.as_view(), name='wishlist_clear'),
    url(r'^(?P<pk>\d+)/remove/$',
        views.WishlistRemoveView.as_view(), name='wishlist_remove'),
)

src/apps/reviews/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, patterns

from reviews.views import add_review, vote_reviews

urlpatterns = patterns("",

    url(r'^add/$', add_review, name='reviews_form',),
    url(r'^vote/(?P<pk>\d+)/add$', vote_reviews, name='vote_reviews',),

)

src/apps/userprofiles/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, url, include


urlpatterns = patterns('userprofiles.views',
    url(r'^register/$', 'registration', name='userprofiles_registration'),
    url(r'^register/complete/$', 'registration_complete',
        name='userprofiles_registration_complete'),
)

if 'userprofiles.contrib.accountverification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^activate/', include('userprofiles.contrib.accountverification.urls')),
    )

if 'userprofiles.contrib.emailverification' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^email/', include('userprofiles.contrib.emailverification.urls')),
    )

if 'userprofiles.contrib.profiles' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        (r'^profile/', include('userprofiles.contrib.profiles.urls')),
    )

urlpatterns += patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', {'template_name': 'userprofiles/login.html'}, name='login'),
    url(r'^logout/$', 'logout', {'template_name': 'userprofiles/logged_out.html'}, name='logout'),
    url(r'^password_change/$', 'password_change',
            {'template_name': 'userprofiles/password_change.html'}, name='password_change'),
    url(r'^password_change/done/$', 'password_change_done',
            {'template_name': 'userprofiles/password_change_done.html'}, name='password_change_done'),
    url(r'^password_reset/$', 'password_reset', {'template_name': 'userprofiles/password_reset.html',
         'email_template_name': 'userprofiles/mails/password_reset_email.html'},
         name='password_reset'),
    url(r'^password_reset/done/$', 'password_reset_done',
            {'template_name': 'userprofiles/password_reset_done.html'}, name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
#    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
#        'password_reset_confirm_uidb36', {'template_name': 'userprofiles/password_reset_confirm.html'},),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'password_reset_confirm', {'template_name': 'userprofiles/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'password_reset_complete',
            {'template_name': 'userprofiles/password_reset_complete.html'},
        name='password_reset_complete'),
)

src/project_src/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.http import HttpResponseServerError
from django.template.loader import render_to_string
from django.template.context import RequestContext
from django.views.generic.base import TemplateView, RedirectView

import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin as default_admin
default_admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="homepage.html",
            get_context_data=lambda: {'is_homepage': True}), name='home_page'),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^accounts/', include('userprofiles.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^contacts/', include('contact_form.urls')),
    url(r'^pages/', include('pages.urls')),
    # url(r'^robots.txt$', include('robots.urls')),
    # for calendar
    # url(r'^area101/jsi18n/', 'django.views.i18n.javascript_catalog'),
    url(r'^admin/', include(default_admin.site.urls)),
)

def error500(request, template_name='500.html'):
    """ Error 500 handler """
    try:
        output = render_to_string(template_name, {}, RequestContext(request))
    except:
        output = "Critical error. Administrator was notified."
    return HttpResponseServerError(output)

# forcing user to configure httpd
if settings.DEBUG:
    if 'rosetta' in settings.INSTALLED_APPS:
        urlpatterns += patterns('',
            url(r'^rosetta/', include('rosetta.urls')),
        )
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns += patterns('',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )
    urlpatterns += patterns('',
        url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico'), name='favicon'),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
        }),
    )
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('', url(r'^', include('bshop.urls')),)

src/apps/bshop/contrib/wishlists/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.core.cache import cache
from django.core.urlresolvers import reverse

from bshop.core.models import TimeStampModel

try:
    User = settings.AUTH_USER_MODEL
except ImportError:
    from django.contrib.auth.models import User

try:
    from django.utils import timezone
except ImportError:
    from datetime import datetime as timezone

"""
https://github.com/jrief/django-shop-wishlists/tree/master/shop_wishlists
"""


@python_2_unicode_compatible
class Wishlist(TimeStampModel):
    """
    Each customer, ie. user may have one or more wishlists to remember items
    for later acquisition.
    """
    user = models.ForeignKey(User, related_name='wishlists')
    name = models.CharField(max_length=30, null=True, blank=True)
    notes = models.TextField(null=True, blank=True,
                help_text=_('Any optional notes on the item (size, color, etc.).'))

    class Meta(object):
        db_table = 'bshop_wishlist'
        verbose_name = _('Wishlist')
        verbose_name_plural = _('Wishlists')

    def __str__(self):
        return u"%s" % self.name
    
    def is_empty(self):
        return self.wl_items.count() == 0

    @property
    def get_display_id(self):
        return '%s-%s%s' % (self.created_at.strftime('%y'), self.created_at.strftime('%m'), self.id)

    def delete_item(self, item_id):
        """
        A simple convenience method to delete an item from the wishlist.
        """
        WishlistItem.objects.get(pk=item_id).delete()
        self.save()
    
    def save(self, *args, **kwargs):
        super(Wishlist, self).save(*args, **kwargs)
        cache_key = 'WISHLISTS_%s' % self.user.pk
        wishlist_set = [wishlist.pk for wishlist in self.user.wishlists.all()]
        cache.set(cache_key, wishlist_set)
    
    def get_absolute_url(self):
        return reverse('wishlist_items', args=[self.pk])


@python_2_unicode_compatible
class WishlistItem(models.Model):
    """
    This is a holder for the item in the wishlist.
    """
    wishlist = models.ForeignKey(Wishlist, verbose_name=_('Wishlist'),
                                 related_name="wl_items")

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    notes = models.TextField(null=True, blank=True,
                help_text=_('Any optional notes on the item (size, color, etc.).'))

    class Meta(object):
        db_table = 'bshop_wishlist_item'
        verbose_name = _('Wishlist item')
        verbose_name_plural = _('Wishlist items')

    def __str__(self):
        return u'%s %s' % (self.product.__class__.__name__, self.product.pk)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product),
                                                              for_concrete_model=False)
        self.object_id = product.pk

    product = property(get_product, set_product)

src/apps/bshop/contrib/wishlists/forms.py
from django.forms import ModelForm

from .models import WishlistItem, Wishlist


class WishlistItemForm(ModelForm):
    """ Form for WishlistItem. """

    class Meta:
        model = WishlistItem
        fields = ['content_type', 'object_id']


class WishlistForm(ModelForm):
    """ Form for Wishlist. """

    class Meta:
        model = Wishlist
        fields = ['name']
    
    def __init__(self, *args, **kwargs):
        super(WishlistForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = True

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlist_form.html
{% load form_snippets_tags %}
<form action="{% url 'wishlist_add' %}" method="post" class="js-ajax-form list-edit-form" data-result=".user-wishlists" data-item="">
	<div class="form-group">
		<div class="input-group">
			<div class="input-group-addon"><i class="fa fa-heart-o"></i></div>
			{{form.name|css_class:"form-control"}}
		</div>
		{{form.name.errors}}
	</div>
{% csrf_token %}
</form>

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlist_list.html
{% extends "userprofiles/profile.html" %}
{% load i18n form_snippets_tags %}
{% block title %}{% trans "Списки желаний" %}{% endblock %}

{% block crumbs %} 
<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
    <a href="{% url 'userprofiles_profile' %}" itemprop="url">
        <span itemprop="title">{% trans "My profile" %}</span>
    </a>
</li>
<li itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
    <span itemprop="title">{% trans 'Списки желаний' %}</span>
</li>  
{% endblock %}

{% block content-title %}{% trans "Списки желаний" %}{% endblock %}

{% block content-body %}
<div class="items-list user-wishlists margBot30">
    {% for wishlist in object_list %}
        {% include "wishlists/includes/wishlist_list_item.html" %}
    {% endfor %}
    <div class="list-empty{% if object_list.count != 0 %} hidden{% endif %}">
        <p>Списки желаний пока не настроены.</p>
        <p>Запланируйте свои покупки с помощью списка желаний.</p>
        <p>Создайте списки желаемых товаров для быстрого доступа к ним в личном кабинете.</p>
    </div>
</div>

<a href="javascript:void(0)" data-target="#wishlistModal" class="btn-default btn btn-add margBot30" data-toggle="modal" data-header="Создать список желаний" data-url="{% url 'wishlist_add' %}">
  <i class="fa fa-plus fa-fw"></i>
 {% trans "Создать список желаний" %}
</a>

{# Wishlist add/edit dialog #}
<div id="wishlistModal" class="modal fade list-edit-dialog" role="dialog" aria-labelledby="wishlistModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="wishlistModalLabel">Создать список желаний</h4>
        </div>
        <div class="modal-body">
           {% include "wishlists/wishlist_form.html" %}
        </div>
        <div class="modal-footer">
           <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</button>
           <button class="btn btn-primary">{% trans "Save" %}</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block sidebar-right %}
    {% with ActiveProfileSb="wishlist" %}
        {% include "userprofiles/includes/left_menu_profile.html" %}
    {% endwith %}
{% endblock sidebar-right %}

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlistitem_add_form.html
{% load i18n %}
{% load url from future %}
{% comment %}
    Form rendered from {% wishlist_add_form <item> %} template tag.
{% endcomment %}
<form action="{% url 'wishlist_add' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="item" value="{{ item.pk }}">
    <input type="submit" value="{% trans 'Add' %}">
</form>

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlistitem_confirm_clear.html
{% extends "base.html" %}

{% load i18n %}
{% load url from future %}

{% block htmltitle %}{% trans 'Clear wishlist' %}{% endblock %}
{% block title %}{% trans 'Clear wishlist' %}{% endblock %}

{% block content %}
    {% blocktrans %}Are you sure you want to remove all items from your wishlist?{% endblocktrans %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="{% trans 'Confirm' %}">
    </form>

    <nav>
        <a href="{% url 'wishlist' %}">{% trans 'Back to the wishlist' %}</a>
    </nav>
{% endblock content %}

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlistitem_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}
{% load url from future %}

{% block htmltitle %}{% trans 'Remove item from wishlist' %}{% endblock %}
{% block title %}{% trans 'Remove item from wishlist' %}{% endblock %}

{% block content %}
    {% blocktrans %}Are you sure you want to remove {{ form.instance }} from your wishlist?{% endblocktrans %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="{% trans 'Confirm' %}">
    </form>

    <nav>
        <a href="{% url 'wishlist' %}">{% trans 'Back to the wishlist' %}</a>
    </nav>
{% endblock content %}

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlistitem_form.html
{% extends "base.html" %}

{% load i18n %}
{% load url from future %}

{% block htmltitle %}{% trans 'Add item to wishlist' %}{% endblock %}
{% block title %}{% trans 'Add item to wishlist' %}{% endblock %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="{% trans 'Add' %}">
    </form>

    <nav>
        <a href="{% url 'wishlist' %}">{% trans 'Back to the wishlist' %}</a>
    </nav>
{% endblock content %}

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlistitem_list.html
{% load i18n %}
{% load url from future %}
{% load wishlists_tags %}

{% comment %}
{% block htmltitle %}{% trans 'Wishlist' %}{% endblock %}
{% block title %}{% trans 'Wishlist' %}{% endblock %}
{% endcomment %}

<ul class="list-unstyled items-list">
    {% for wishlist_item in object_list %}
        <li class="list-item">
        	<a href="javascript:void(0)" class="pull-right item-remove" title="{% trans 'Delete' %}" data-url="{% url 'wishlist_remove' wishlist_item.pk %}"><i class="fa fa-remove"></i></a>
            <a href="{{ wishlist_item.product.get_absolute_url }}"><i class="fa fa-shopping-cart"></i> {{ wishlist_item }}</a>
            {#{% wishlist_remove_form wishlist_item.item %}#}
        </li>
        {% if forloop.last %}
        <li class="list-empty hidden">
	        <p>Список пуст</p>
	    </li>
        {% endif %}
    {% empty %}
    <li class="list-empty">
        <p>Список пуст</p>
    </li>
    {% endfor %}
</ul>

<nav>
    {#<p><a href="{% url 'wishlist_add' %}">{% trans 'Add item to wishlist' %}</a></p>#}
    <p><a href="javascript:void(0)" class="js-ajax-link" data-result=".wishlist-items" data-method="POST" data-url="{% url 'wishlist_clear' current_wishlist.pk %}"><i class="fa fa-remove"></i> {% trans 'Очистить' %}</a></p>
</nav>

src/apps/bshop/contrib/wishlists/templates/wishlists/wishlistitem_remove_form.html
{% load i18n %}
{% load url from future %}
{% comment %}
    Form rendered from {% wishlist_remove_form <item> %} template tag.
{% endcomment %}
<form action="{% url 'wishlist_remove' pk=item.wishlistitem_set.all.0.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="{% trans 'Remove' %}">
</form>